<h3>Arithematic Operations Using Numpy</h3>

In [ ]:
import numpy as np

In [56]:
a = np.array(range(5))
b = np.array(range(5,10))
print("a:",a)
print("b:",b)
sum_of_np_arrays = np.add(a,b)
print("Sum:",sum_of_np_arrays)

a: [0 1 2 3 4]
b: [5 6 7 8 9]
Sum: [ 5  7  9 11 13]


In [58]:
a = np.array(range(15,20))
b = np.array(range(5))
print("a:",a)
print("b:",b)
substract_of_np_arrays = np.subtract(a,b)
print("Subtract:",substract_of_np_arrays)

a: [15 16 17 18 19]
b: [0 1 2 3 4]
Subtract: [ 5  7  9 11 13]


In [90]:
a = np.array(range(15,20))
b = np.array(range(5))
print("a:",a)
print("b:",b)
mul_of_np_arrays = np.multiply(a,b)
print("Subtract:",mul_of_np_arrays)

a: [15 16 17 18 19]
b: [0 1 2 3 4]
Subtract: [ 0 16 34 54 76]
[ 0 16 34 54 76]


In [110]:
a = np.array([[2,4,6,8,10],[12,14,16,18,20]])
b = np.array(range(10,15))
print("a:",a)
print("b:",b)
divide_of_np_arrays = np.divide(a,b)
print("Divide:",divide_of_np_arrays)

a: [[ 2  4  6  8 10]
 [12 14 16 18 20]]
b: [10 11 12 13 14]
Divide: [[0.2        0.36363636 0.5        0.61538462 0.71428571]
 [1.2        1.27272727 1.33333333 1.38461538 1.42857143]]


In [116]:
a = np.array([[2,4,6,8,10],[12,14,16,18,20]])
b = np.array(range(10,15))
print("a:",a)
print("b:",b)
power_of_np_arrays = np.power(a,b)
print("POwer:",power_of_np_arrays)

a: [[ 2  4  6  8 10]
 [12 14 16 18 20]]
b: [10 11 12 13 14]
POwer: [[               1024             4194304          2176782336
         549755813888     100000000000000]
 [        61917364224       4049565169664     281474976710656
    20822964865671168 1638400000000000000]]


<h3> Statistical Functions Using Numpy </h3>

In [161]:
arr=np.array([[1,2,3],[3,4,5],[6,7,8]])
print("Median:",np.median(arr))

Median: 4.0


In [159]:
arr=np.array([1,2,3,3,4,5,6,7,8])
print("Median:",np.median(arr))

Median: 4.0


In [155]:
arr=np.array([[1,2,3],[3,4,5],[6,7,8]])
print("Mean:",np.mean(arr))
# Manual way of finding Mean
print("Mean: {}".format(sum(sum(arr)/len(arr))/len(sum(arr)/len(arr))))

Mean: 4.333333333333333
Mean: 4.333333333333333


In [157]:
arr=np.array([[1,2,3],[3,4,5],[6,7,8]])
print("Standard Deviation:",np.std(arr))

Standard Deviation: 2.211083193570267


In [163]:
arr=np.array([[1,2,3],[3,4,5],[6,7,8]])
print("Variance:",np.var(arr))

Variance: 4.888888888888889
