In [123]:
import numpy as np

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print('No of Dimenstions:{}\nShape:{}\nSize:{}\nArray DataType:{}\nTotal Bytes:{}\nData:{}'.format(arr.ndim,arr.shape,arr.size,arr.dtype,arr.itemsize,arr.data))

In [17]:
print("Access Numpy Data")
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print("Items:",arr[i][j])

Access Numpy Data
Items: 1
Items: 2
Items: 3
Items: 4
Items: 5
Items: 6


In [51]:
print("Re-Shaping the Array\n")
arr=np.array(range(12))
arr=arr.reshape(3,4)
print(arr,"\n")
print("Reshaping 4d Array:\n\n",arr.reshape(4,3))

Re-Shaping the Array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Reshaping 4d Array:

 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [59]:
print("Converting the Array to 1D")
arr=arr.reshape(4,3)
print("Before Flatterning")
print(arr)
print("After Flatterning")
print(arr.flatten())

Converting the Array to 1D
Before Flatterning
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After Flatterning
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [73]:
print("Transpose an Array")
arr=arr.reshape(4,3)
print("Before Transpose")
print(arr,arr.shape)
print("After Transpose")
arr=arr.transpose()
print(arr,arr.shape)

Transpose an Array
Before Transpose
[[ 0  3  6]
 [ 9  1  4]
 [ 7 10  2]
 [ 5  8 11]] (4, 3)
After Transpose
[[ 0  9  7  5]
 [ 3  1 10  8]
 [ 6  4  2 11]] (3, 4)


In [ ]:
print("Working Assignment - In Class")

In [91]:
temparatures=np.array([75.2,77.1,74.5,79.3,82.6,81.2,77.8])
temparatures=temparatures.reshape(7,1)

In [121]:
print('No of Dimenstions:{}\nShape:{}\nSize:{}\nArray DataType:{}\nTotal Bytes:{}\nData:{}'.format(temparatures.ndim,temparatures.shape,temparatures.size,temparatures.dtype,temparatures.itemsize,temparatures.data))
print("Data In Memory")
for i in range(temparatures.shape[0]):
    for j in range(temparatures.shape[1]):
        print("Temp on {}:{}".format(j+1,temparatures[i][j]))

No of Dimenstions:2
Shape:(1, 7)
Size:7
Array DataType:float64
Total Bytes:8
Data:<memory at 0x106995a40>
Data In Memory
Temp on 1:75.2
Temp on 2:77.1
Temp on 3:74.5
Temp on 4:79.3
Temp on 5:82.6
Temp on 6:81.2
Temp on 7:77.8


In [97]:
temparatures=temparatures.flatten()
print(temparatures)

[75.2 77.1 74.5 79.3 82.6 81.2 77.8]


In [131]:
temparatures=temparatures.reshape(7,1)
print(temparatures)
print("Shape:",temparatures.shape)
temparatures=temparatures.transpose()
print(temparatures)
print("Shape:",temparatures.shape)

[[75.2]
 [77.1]
 [74.5]
 [79.3]
 [82.6]
 [81.2]
 [77.8]]
Shape: (7, 1)
[[75.2 77.1 74.5 79.3 82.6 81.2 77.8]]
Shape: (1, 7)
