In [3]:
import numpy as np

In [21]:
arr=np.array([[1,2,3],[4,5,6]])
print('No of Dimenstions:{}\nShape:{}\nSize:{}\nArray DataType:{}\nTotal Bytes:{}\nData:{}'.format(arr.ndim,arr.shape,arr.size,arr.dtype,arr.itemsize,arr.data))

No of Dimenstions:2
Shape:(2, 3)
Size:6
Array DataType:int64
Total Bytes:8
Data:<memory at 0x106766b50>


In [17]:
print("Access Numpy Data")
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print("Items:",arr[i][j])

Access Numpy Data
Items: 1
Items: 2
Items: 3
Items: 4
Items: 5
Items: 6


In [51]:
print("Re-Shaping the Array\n")
arr=np.array(range(12))
arr=arr.reshape(3,4)
print(arr,"\n")
print("Reshaping 4d Array:\n\n",arr.reshape(4,3))

Re-Shaping the Array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Reshaping 4d Array:

 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [59]:
print("Converting the Array to 1D")
arr=arr.reshape(4,3)
print("Before Flatterning")
print(arr)
print("After Flatterning")
print(arr.flatten())

Converting the Array to 1D
Before Flatterning
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After Flatterning
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [71]:
print("Transpose an Array")
arr=arr.reshape(4,3)
print("Before Transpose")
print(arr,arr.shape)
print("After Transpose")
arr=arr.transpose()
print(arr,arr.shape)

Transpose an Array
Before Transpose
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)
After Transpose
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]] (3, 4)
