<h1> Indexing </h1>

In [3]:
import numpy as np

In [55]:
array = np.array(range(1,16))
array=array.reshape(5,3)
print("Array:\n",array)
print("\nAccessing 2D Array Elements")
for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        print("Elements of Array at row {}:{}".format(i,array[i][j]))
print("\nNegative Indexing Example")
print("Element At Index ({},{}): {}".format(3,2,array[-2][-1]))

Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

Accessing 2D Array Elements
Elements of Array at row 0:1
Elements of Array at row 0:2
Elements of Array at row 0:3
Elements of Array at row 1:4
Elements of Array at row 1:5
Elements of Array at row 1:6
Elements of Array at row 2:7
Elements of Array at row 2:8
Elements of Array at row 2:9
Elements of Array at row 3:10
Elements of Array at row 3:11
Elements of Array at row 3:12
Elements of Array at row 4:13
Elements of Array at row 4:14
Elements of Array at row 4:15

Negative Indexing Example
Element At Index (3,2): 12


In [57]:
array = np.array(range(1,16))
print("Array:\n",array)
print("\nAccessing 1D Array Elements")
for i in range(array.shape[0]):
    print("Elements of Array:",array[i])

Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Accessing 1D Array Elements
Elements of Array: 1
Elements of Array: 2
Elements of Array: 3
Elements of Array: 4
Elements of Array: 5
Elements of Array: 6
Elements of Array: 7
Elements of Array: 8
Elements of Array: 9
Elements of Array: 10
Elements of Array: 11
Elements of Array: 12
Elements of Array: 13
Elements of Array: 14
Elements of Array: 15


In [79]:
array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]])
print("3D Array:",array[1,1,0])

TypeError: Field elements must be 2- or 3-tuples, got '[7, 8, 9]'