In [3]:
import numpy as np
import pandas as pd

In [3]:
array1=np.array(range(0,9))
array1=array1.reshape(3,3)
array2=np.array(range(9,18))
array2=array1.reshape(3,3)

In [5]:
print(array1,array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
rows=input("Enter the Number of Rows\n")
columns=input("Enter Number of Columns\n")
array3=[[int(input()) for i in range(int(columns))]for i in range(int(rows))]

In [11]:
result=[]
for r in range(3):
    temp=[]
    for c in range(3):
        temp.append(array1[r][c]+array2[r][c])
    result.append(temp)
print(np.array(result))

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [37]:
result=np.array([0]*9)
result=result.reshape(3,3)
for r in range(3):
    for c in range(3):
        result[r][c]=array1[r][c]+array2[r][c]
print(np.array(result))

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [4]:
result=np.array([0]*9)
result=result.reshape(3,3)
for r in range(3):
    for c in range(3):
        result[r][c]=c*array1[r][c]
print(np.array(result))

[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]


### Multiplication of Matrix

In [56]:
array1=np.array([3,7,4,9])
array1=array1.reshape(2,2)
array2=np.array([6,2,5,8])
array2=array2.reshape(2,2)
print(array1,"\nX\n",array2)
result=[]
for r in range(2):
        for i in range(len(array2)):
            temp=0
            for c in range(2):
                temp+=array2[c][i] * array1[r][c]
            result.append(temp)
print("result:\n",np.array(result).reshape(2,2))

[[3 7]
 [4 9]] 
X
 [[6 2]
 [5 8]]
result:
 [[53 62]
 [69 80]]


In [62]:
array1=np.array([3,7,4,9])
array1=array1.reshape(2,2)
array2=np.array([6,2,5,8])
array2=array2.reshape(2,2)
print(array1,"\nX\n",array2)
result=np.array([0]*4).reshape(2,2)
for r in range(2):
    for c in range(2):
        temp=0
        for i in range(2):
                temp+=array1[r][i] * array2[i][c]
                result[r][c]=temp
print("result:\n",np.array(result).reshape(2,2))

[[3 7]
 [4 9]] 
X
 [[6 2]
 [5 8]]
result:
 [[53 62]
 [69 80]]


## Transpose matrix

In [4]:
array1=np.array(range(0,9))
array1=array1.reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
result=np.array([[0 for i in range(3)] for i in range(3)])
print(result)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [31]:
for i in range(len(result)):
    for j in range(len(result[0])):
        result[j][i]=array1[i][j]
print(result)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


### Non Equal Tranpose

In [5]:
array1=np.array(range(0,12))
array1=array1.reshape(3,4)
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
result=np.array([[0 for i in range(len(array1))] for i in range(len(array1[0]))])
print(result)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
print("Before Transpose:\n",array1)
for i in range(len(array1[0])):
    for j in range(len(array1)):
        result[i][j]=array1[j][i]
print("After Transpose:\n",result)

Before Transpose:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Finding Determinant of Matrix